274 add support for solidly uni v2 style pools
bancorprotocol/fastlane-bot pull request #282
Opened 2024-01-04 13:19 UTC by Lesigh-3100

2024-01-12 02:53 UTC, mikewcasale commented on fastlane_bot/data/blockchain_data/ethereum/tokens.csv
is there a reason we are adding more tokens with the code changes?

2024-01-12 02:54 UTC, mikewcasale commented on fastlane_bot/data/blockchain_data/coinbase_base/uniswap_v3_event_mappings.csv
similarly with tokens.csv, are these additions needed to support the code changes?

2024-01-12 02:55 UTC, mikewcasale commented on fastlane_bot/data/blockchain_data/coinbase_base/uniswap_v2_event_mappings.csv
similarly with tokens.csv, are these additions needed to support the code changes?

2024-01-12 02:55 UTC, mikewcasale commented on fastlane_bot/data/blockchain_data/coinbase_base/tokens.csv
similarly with tokens.csv, are these additions needed to support the code changes?

2024-01-12 02:55 UTC, mikewcasale commented on fastlane_bot/data/blockchain_data/coinbase_base/static_pool_data.csv
similarly with tokens.csv, are these additions needed to support the code changes?

2024-01-12 03:00 UTC, mikewcasale requested changes
Please only include necessary changes to the csv files so that we don't inadvertently introduce errors there.

2024-01-15 08:59 UTC, Lesigh-3100 commented on fastlane_bot/data/blockchain_data/ethereum/tokens.csv
No - this is not necessary

2024-01-15 09:01 UTC, Lesigh-3100 commented on fastlane_bot/data/blockchain_data/coinbase_base/static_pool_data.csv
This specifically does need to be added - yes. There were significant important changes to the static data on Base.

2024-01-15 09:02 UTC, Lesigh-3100 commented on fastlane_bot/data/blockchain_data/coinbase_base/tokens.csv
Not entirely necessary - could be removed

2024-01-15 09:02 UTC, Lesigh-3100 commented on fastlane_bot/data/blockchain_data/coinbase_base/uniswap_v2_event_mappings.csv
This should be included as it adds more pools available to trade on. Not a -requirement- of the code to operate, but important.

2024-01-15 09:03 UTC, Lesigh-3100 commented on fastlane_bot/data/blockchain_data/coinbase_base/uniswap_v3_event_mappings.csv
This should be included as it adds more pools available to trade on. Not a -requirement- of the code to operate, but important.

2024-01-22 11:10 UTC, mikewcasale approved these changes
Looks good

2024-01-22 11:13 UTC, merged