343 remove test stubs
bancorprotocol/fastlane-bot pull request #344
Opened 2024-02-01 13:15 UTC by barakman

Handles issue #343

2024-02-02 13:01 UTC, mikewcasale requested changes
Why keep `AM_SINGLE` at all at this point? In bot.py I'd suggest removing the only usage as follows, and then delete the AM_SINGLE attribute definition at class level:

```python
def _find_arbitrage(
        self,
        flashloan_tokens: List[str],
        CCm: CPCContainer,
        arb_mode: str = 'single',
        randomizer=int
    ) -> dict:
        random_mode = self.AO_CANDIDATES if randomizer else None
        arb_finder = self._get_arb_finder(arb_mode)
        finder = arb_finder(
            flashloan_tokens=flashloan_tokens,
            CCm=CCm,
            mode="bothin",
            result=random_mode,
            ConfigObj=self.ConfigObj,
        )
        return {"finder": finder, "r": finder.find_arbitrage()}
```

2024-02-02 13:41 UTC, barakman commented
> Why keep `AM_SINGLE` at all at this point? In bot.py I'd suggest removing the only usage as follows, and then delete the AM_SINGLE attribute definition at class level:
> 
> ```python
> def _find_arbitrage(
>         self,
>         flashloan_tokens: List[str],
>         CCm: CPCContainer,
>         arb_mode: str = 'single',
>         randomizer=int
>     ) -> dict:
>         random_mode = self.AO_CANDIDATES if randomizer else None
>         arb_finder = self._get_arb_finder(arb_mode)
>         finder = arb_finder(
>             flashloan_tokens=flashloan_tokens,
>             CCm=CCm,
>             mode="bothin",
>             result=random_mode,
>             ConfigObj=self.ConfigObj,
>         )
>         return {"finder": finder, "r": finder.find_arbitrage()}
> ```

Thanks, that was my thought as well, but I noticed that `AM_SINGLE` was still used in several other places (primarily in test files), so I thought I'd keep the amount of changes in this PR at the minimum necessary.
But now that you mention it, I'll have another look to see if I can clear that up as well.

2024-02-05 11:50 UTC, mikewcasale approved these changes

2024-02-11 21:17 UTC, mikewcasale requested changes
I'm not convinced the pro's outweigh the con's with all these changes. Convince me otherwise - and also address the specific comments concerning `rawTransaction` usage in multiple places.

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/helpers/txhelpers.py
then again the following function appears to expect the signed tx object and not simply the `rawTransaction` value:

```python
def submit_regular_transaction(self, signed_tx) -> str:
        """
        Submits the transaction to the blockchain.

        :param signed_tx: the signed transaction to be submitted to the blockchain

        returns: the transaction hash of the submitted transaction
        """

        self.ConfigObj.logger.info(
            f"[helpers.txhelpers.submit_regular_transaction] Attempting to submit transaction {signed_tx}"
        )

        return self._submit_transaction(self.web3.eth.send_raw_transaction(signed_tx.rawTransaction))
```

where the effect of the above I assume is `signed_tx.rawTransaction.rawTransaction` which doubtfully works.

More generally, a lot of these changes seem high risk and Im not sure there is a commensurate benefit to warrant taking such risks at the moment...

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/tests/nbtest/test_038_TestBancorV3Mode.py
this entire folder should actually just be deleted instead of modifying files

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/tests/nbtest/test_039_TestMultiMode.py
see above

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/tests/nbtest/test_040_TestSingleMode.py
see above

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/tests/nbtest/test_050_TestBancorV2.py
see above

2024-02-11 21:17 UTC, mikewcasale commented on fastlane_bot/tests/nbtest/test_901_TestMultiTriangleModeSlow.py
see above

2024-02-11 21:17 UTC, mikewcasale commented on resources/NBTest/_DISABLED/_NBTest_011_TestingRun_DISABLED.py
Again, this entire folder should just be deleted / removed from the repo, I don't see the point of changing stuff that has precisely zero effect on anything... 

More generally, there are a lot of implications for these changes on the testing side. Why the rush to merge this now, right before we plan to switch over to a new testing infrastructure, which will remove all the stale files and folders, and should allow for easier isolated testing of the critical changes within `bot.py` and `txhelpers.py`.

2024-02-11 21:26 UTC, barakman commented on fastlane_bot/helpers/txhelpers.py
> +            test_fake_gas=False,
Maybe, but it is not related to this already-large PR, so I prefer to keep out anything which isn't directly a part of it.

2024-02-11 21:28 UTC, barakman commented on fastlane_bot/helpers/txhelpers.py
> +        signed_arb_tx = self.sign_transaction(arb_tx).rawTransaction
This is exactly what this PR fixes.
The `signed_arb_tx` variable is the (original) value returned from the call to function `self.sign_transaction`.

2024-02-11 21:30 UTC, barakman commented on fastlane_bot/helpers/txhelpers.py
Exactly the opposite of your interpretation above.
This PR is aimed at solving the "`rawTransaction.rawTransaction`" issue.

2024-02-11 21:31 UTC, barakman commented on fastlane_bot/tests/nbtest/test_039_TestMultiMode.py
see above

2024-02-11 21:31 UTC, barakman commented on fastlane_bot/tests/nbtest/test_040_TestSingleMode.py
see above

2024-02-11 21:31 UTC, barakman commented on fastlane_bot/tests/nbtest/test_050_TestBancorV2.py
see above

2024-02-11 21:31 UTC, barakman commented on fastlane_bot/tests/nbtest/test_901_TestMultiTriangleModeSlow.py
see above

2024-02-11 21:32 UTC, barakman commented on resources/NBTest/_DISABLED/_NBTest_011_TestingRun_DISABLED.py
The reason is explained above.
The otherwise result is that these tests will start failing.

2024-02-12 13:21 UTC, barakman commented on fastlane_bot/helpers/txhelpers.py
> +        signed_arb_tx = self.sign_transaction(arb_tx).rawTransaction
Strange. I've actually removed that line in the code right when I started working on the whole thing (like, literally the very first thing that I did there).
It must have found its way back as part of one of the manual merges that I needed to do as a result of other changes being pushed to the repo.
Tx for pointing out!

2024-02-12 14:04 UTC, mikewcasale commented on fastlane_bot/helpers/txhelpers.py
> +        signed_arb_tx = self.sign_transaction(arb_tx).rawTransaction
Looks fixed now, thx

2024-02-12 14:06 UTC, mikewcasale approved these changes

2024-02-12 14:21 UTC, merged