Simplify and improve event-fetching
bancorprotocol/fastlane-bot pull request #364
Opened 2024-02-08 16:19 UTC by barakman

1. Simplify the code for fetching events.
3. Avoid fetching duplicated events.

2024-02-09 13:53 UTC, zavelevsky approved these changes
LGTM but please run and compare the results

2024-02-12 14:14 UTC, mikewcasale requested changes
It seems like the outputs for all of the removed functions could be tested against the new function(s), in order to ensure equivalent outputs. Please provide such tests or explain your reasoning for not providing them.

2024-02-12 14:22 UTC, barakman commented
> It seems like the outputs for all of the removed functions could be tested against the new function(s), in order to ensure equivalent outputs. Please provide such tests or explain your reasoning for not providing them.

I've done it locally. Adding a test for it means preserving old code, which doesn't make much sense.

2024-02-12 15:32 UTC, mikewcasale approved these changes

2024-02-12 17:21 UTC, merged