Update carbon_v1.py
bancorprotocol/fastlane-bot pull request #423
Opened 2024-03-12 12:23 UTC by Lesigh-3100

Issue described in: https://github.com/bancorprotocol/fastlane-bot/issues/419

2024-03-12 12:55 UTC, barakman requested changes

2024-03-12 13:00 UTC, barakman commented on fastlane_bot/events/pools/carbon_v1.py
> +
Of course, I don't disagree that the previous code was bad by itself in several different aspects, such as:
- In function `parse_orders`, returning two different types
- In this function, deciding the course of action based on the input type
- In this function, assuming that either both inputs are of type `list` or both inputs are not of type `list`

2024-03-12 13:51 UTC, Lesigh-3100 commented on fastlane_bot/events/pools/carbon_v1.py
> +
Updated this - could you please take another look?

2024-03-12 13:52 UTC, barakman requested changes

2024-03-12 13:52 UTC, barakman commented on fastlane_bot/events/pools/carbon_v1.py
> +        data["B_1"] = order1[3]
Why not do everything in the same way that you are handling `cid`?

2024-03-13 08:51 UTC, Lesigh-3100 commented
After testing I found that this code functions as-is. The issue is somewhere else in the code. Closing PR.

2024-03-13 08:51 UTC, closed without merging