Hotfix - Carbon strategies duplicated
bancorprotocol/fastlane-bot pull request #522
Opened 2024-04-07 17:24 UTC by Lesigh-3100

Bugfix for issue: https://github.com/bancorprotocol/fastlane-bot/issues/521

2024-04-07 18:06 UTC, barakman requested changes
No tests.
How can you be certain that this PR fixes the problem?
How can you be certain that this PR doesn't create another problem?

2024-04-07 18:06 UTC, barakman commented on fastlane_bot/events/managers/pools.py
> +        pool_info["cid"] = get_pool_cid(pool_info, self.cfg.CARBON_V1_FORKS)
Function `get_pool_cid` calls function `get_cid_base`.

And function `get_cid_base` handles the CIDs differently for carbon v1 forks and for all other cases:
```
    return (
            args["exchange_name"]
            + " "
            + str(args["strategy_id"])
    ) if args["exchange_name"] in carbon_v1_forks else (
            args["exchange_name"]
            + " "
            + args["pair_name"]
            + " "
            + str(args["fee"])
    )
```
Are you sure that this doesn't yield the exact same problem?


Module pools / Class PoolManager / Function pool_descr_from_info
Module pools / Class PoolManager / Function add_pool_info
Module utils / Global Function get_cid_base

2024-04-08 09:39 UTC, zavelevsky approved these changes
LGTM

2024-04-08 10:09 UTC, barakman approved these changes

2024-04-08 10:36 UTC, merged