Update fusionx details info
bancorprotocol/fastlane-bot pull request #525
Opened 2024-04-08 10:14 UTC by NIXBNT

Successful Tenderly test tx w splitter

2024-04-08 10:46 UTC, Lesigh-3100 commented on fastlane_bot/config/network.py
> +    CARBON_V1_FORKS = [CARBON_V1_NAME, CARBON_V1_FORK1_NAME]
I think this can be removed

2024-04-08 10:46 UTC, Lesigh-3100 commented on fastlane_bot/config/constants.py
> +CARBON_V1_FORK1_NAME = "fusionx_carbon"
I believe this can be removed

2024-04-09 13:46 UTC, barakman requested changes

2024-04-09 13:46 UTC, barakman commented on fastlane_bot/config/network.py
> +from .constants import CARBON_V1_NAME
Not clear why this is needed here (no other change in this PR seems to be using it)

2024-04-09 13:46 UTC, barakman commented on fastlane_bot/config/network.py
> +    CARBON_V1_FORKS = []
Not clear why this is needed here (why not just create it in the class's post-init function?)

2024-04-10 15:23 UTC, barakman approved these changes

2024-04-10 15:25 UTC, merged