Deterministic testing integration
bancorprotocol/fastlane-bot pull request #671
Opened 2024-05-23 05:15 UTC by NIXBNT

The deterministic testing is a critical component to the testing infrastructure.
This PR rebases onto the release candidate with some important fixes.
Most critically, an additional logging component has be (re)added into the transaction txt files that are created following a successful transaction

2024-05-23 05:16 UTC, NIXBNT commented on fastlane_bot/bot.py
> +                            json.dump(log_entry, f, indent=4)
@barakman changed this to a json dump.
The tx_details one looks a little odd but it is functional

2024-05-23 05:18 UTC, NIXBNT commented on fastlane_bot/bot.py
> +            return None, None, None
The log_dict is returned alongside the txhash and tx_reciept in the txhelpers.
@barakman can you verify this is correct

2024-05-24 09:35 UTC, barakman requested changes
This PR should not be merged until PR #651 is

2024-05-24 09:35 UTC, barakman commented on fastlane_bot/data/abi.py
> +        "outputs":[{"internalType":"uint256","name":"","type":"uint256"}]
These are write functions (changing contract state).
They are not supposed to be used by the bot, even though they can be executed in read-only mode (aka *static call*).
If this is indeed how you're using them, then there is very likely a better way (i.e., calling an actual read function in the same contract).

2024-05-24 09:35 UTC, barakman commented on fastlane_bot/bot.py
> +        tx_hash, tx_receipt, log_dict = self._handle_trade_instructions(CCm, arb_mode, r, replay_from_block)
No changes in this file until PR #651 is merged

2024-05-24 09:35 UTC, barakman commented on fastlane_bot/helpers/txhelpers.py
> +            return tx_hash, tx_receipt, log_dict
Passing an additional input parameter just in order to return it seems futile.
You can easily determine on the caller function that `log_dict` is valid if and only if `tx_hash` and `tx_receipt` are valid.

2025-11-17 09:43 UTC, closed without merging