Add xfai carbon deployment
bancorprotocol/fastlane-bot pull request #689
Opened 2024-06-16 10:46 UTC by Lesigh-3100

- Added support for XFai's Carbon deployment!
- Updated Static data for Linea.
- Fixed an issue that affected gathering pool data for Xfai's existing exchange.

2024-06-16 11:26 UTC, barakman requested changes

2024-06-16 11:26 UTC, barakman commented on fastlane_bot/events/exchanges/solidly_v2/xfai_v0.py
> +    def get_core_abi(self):
No need for this function, just place `XFAI_V0_POOL_ABI` directly where you call it below.

2024-06-17 09:48 UTC, barakman approved these changes

2024-06-17 17:21 UTC, zavelevsky approved these changes

2024-06-17 17:21 UTC, merged